services:
  comfyui-test:
    image: lyspal/comfyui:1.0.0
    ports:
      - "8188:8188"
    volumes:
      - custom_nodes:/app/comfyui/custom_nodes
      - models:/app/comfyui/models
      - output:/app/comfyui/output
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu, compute, utility ]
    restart: unless-stopped

volumes:
  custom_nodes:
  models:
  output:
